### ISSUE TITLE
Mc Lighting Disconnected

### ISSUE THREAD

**Issue by Roamin64** [toblum/McLightingUI#2]
I uploaded "index2.htm" but it always remains disconnected ? The page loads fine with the new UI , but in the top right corner it says Mc Lighting disconnected and no modes work. "index.htm" still works fine , but I can't figure out what i'm doing wrong ? I tried on firefox and edge on pc , and firefox on android, all same result.   Otherwise the new UI looks awesome.

**Comment by toblum** [comment]
Hi @Roamin64,

could you please open the webpage in a desktop browser, e.g. chrome, hit F12 to open the developer tools and reload the page. Then please copy over the outputs in console tab. There will be more informations on what is happening.

Best regards
Tobias

**Comment by Roamin64** [comment]
I did not try with Chrome yesterday , but using chrome it can actually connect. The very first time it connected it only used part of my strip , about 1/3 of 166 LEDs.

This is the console outpout in firefox : https://pastebin.com/d9z2qfSW

This is the console output in chrome : https://pastebin.com/xyfMsv84

Everything seems to work so far using chrome.

**Comment by Roamin64** [comment]
Here's a console output from microsoft's Edge browser : https://pastebin.com/HJU8LWDD        (Can't connect)

**Comment by Roamin64** [comment]
Also connects properly with chrome on android.

**Comment by toblum** [comment]
Hi @Roamin64,

honestly, I did no cross-browser tests so far. 
I published a new version that should support edge now, as well as Firefox and chome, no IE:
https://github.com/toblum/McLightingUI/blob/master/dist/index2.htm

Could you give this a try?

Regards
Tobias

**Comment by Roamin64** [comment]
All right! @toblum It now works in firefox and edge on my pc and firefox on android. Great Work! I haven't seen any issues so far with the UI. 

What is index2_meshy.htm ?

It would be nice if there was a way to set colors 2 and 3 for use with the effects that have other colors. Maybe a simple input box where we type the color in hex.

Is there a way to force Mc Lighting to return to the AP setup mode ? 

Thanks a lot for all this great work. I use Mc Lighting in 2 projects, One is an 18 feet long wall with white curtains and 2 strips of 166 LEDs in parallel, bottom and top. The other is a framed heart that I gave to my girlfriend. She will enjoy the new UI a lot.

**Comment by Roamin64** [comment]
Whatever index2_meshy.htm is , it doesn't connect properly.

**Comment by toblum** [comment]
The index2_meshy is a version especially for the still experimental MeshyMclighting madeby the great @debsahu.

AP mode should be reachable via: http://<mclighting_ip>/start_config_ap

You can find more informations here:
https://github.com/toblum/McLighting/tree/experimental/Arduino/MeshyMcLighting

**Comment by Roamin64** [comment]
@toblum Ok , although the latest version of index2.htm works fine with my setup , on my girlfriend's setup , it won't connect. It hangs at step 2/4 , with the following console output : 

https://pastebin.com/AVsAnAhg

Something about uistate.json not found. On both firefox and chrome.

**Comment by toblum** [comment]
Hi @Roamin64,

thank you for reporting this. There was a error when the settings are not yet present. I missed that.
I prepared a new version. Could you try this out: https://github.com/toblum/McLightingUI/blob/master/dist/index2.htm

Best regards
Tobias

**Comment by Roamin64** [comment]
I don't have access to my girlfriend's setup right now , so I erased my wemos , then uploaded yesterday's version of index2 and I had the same error. Then I uploaded your latest version and the error went away and it connected and worked. I've only tested on firefox on both pc and android. 

Concerning the UI , i've been playing around with it a bit more in the past day and there are a few details. 

- The overall UI is not as responsive as V2. Everything in V2 responds quickly , sliders , color wheel , mode selection. There is a considerable lag on all the devices i've tested running index2

- The sliders are difficult to move. With a mouse and pc its ok , but on mobile even on my Note 5's big screen I have a hard time using just a finger to slide, it easier using the pen but kind of inconvenient. It seems to be related to the input lag though , if I leave my finger longer before I start to slide I get better results.

- I preferred seeing directly on top of each slider knob the current value, even though it is shown in the color box.

- The speed and brightness sliders seem to have increment locks in them, and have no indication of their current value , for reference for a future exact setup of a mode. Also some mode are very sensitive with their speed in my setup (166 LEDs string) and there can sometimes be a difference in a single increment in v2. For example , one of my favorite fire flicker effect I use precisely 61 as its value. Strobe light on my setup will be at its fastest at 254 , but won't blink at all at 255. If the increments are locked I can't get that fine tuning, I believe.

- I tried the /start_config_ap command , but there seems to be issues. Although the MC Lighting AP does re-appear ,and I can connect to it, it times out trying to access 192.168.4.1 so it is impossible to join a new network. Unplugging and replugging returns the connection to the previous network and the system behaves normally.

If there are any thing else I can help with , let me know.

**Comment by toblum** [comment]
Hi @Roamin64,

thank you for your feedback. I see that the new uI takes some seconds to load, but stays responsive in my tests, even on slower devices. On which devices did you test? And what version / configuration of McLighting did you use?

I changed the behaviour of the sliders a bit and added the value to the sliders.

I can reproduce the behaviour of the strobe with 255 speed, but I can't find the reason why this happens at the moment. Maybe it's too fast for the ESP.

Another option for reconnecting is calling /reset_wlan. This resets WLAn settings and reboots.

Best regards
Tobias
