### ISSUE TITLE
new functionality

### ISSUE THREAD

**Issue by marqss81** [toblum/McLightingUI#3]
Hello!
First at all I want to thank you for great job with this project! It's fantastic! :) I was looking for something similar for some time for making a wall light :) Still, I have some ideas which the project could benefit from :) (I'm no programmer, can't simply do this by myself :( )
Here we go:
- IR remote control - ESP8266 have a lot of free gpio-s, we could use one of them for receiving commands from cheap (and lying around old ones, also from ready-to-use led strips) IR remote controls. Wifi and mobile is nice, but small remote could be also good. This solution would need support of learnig IR codes from remote to use and we could work without wifi,
- almost every time after power reconnect node is unable to connect with wifi. I have some other things with esp8266 which needs working wifi (esp mega with some sensors) - it always connect to wifi without any problem. Do we really need wifi every time for working? We have one button for on/off the strip. Why we couldn't use another to switch effects next/prev?

Keep your good work up!

Best regards,
Marek

**Comment by toblum** [comment]
HI @marqss81,

thank you for your feedback. I added your suggestion at https://github.com/toblum/McLighting/blob/master/README.md. If you got something implemented yourself, let me know.

Disabling WiFi if no connection could be made is not so straightforward. I got this already on the list. We will see what we could do.

Best regards
Tobias

**Comment by bpohvoodoo** [comment]
IR functionality is implemented in https://github.com/FabLab-Luenen/McLighting
but no learning yet. You have to look at the logs and the put the ir-codes into the definitions.
