### ISSUE TITLE
ESP-01 ESP8266

### ISSUE THREAD

**Issue by elzershark** [toblum/McLightingUI#4]
Hab die index2 Seite mal probiert mit einem ESP-01.
Leider bleibt die Seite Blank.
Die normale index Datei wird angezeigt.
Bei anderen Platinen funktioniert es.

In Console steht nichts.

Ich denke mal das liegt an der Größe der Datei !?

**Comment by toblum** [comment]
Hallo @elzershark,

der ESP-01 hat meist nur 512 kB Speicher. Das reicht leider nicht für die neue index2-Seite. 

Viele Grüße
Tobias
