### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by IIAIronWolf** [toblum/McLightingUI#5]
I have loaded the new UI into my browser just to see how it looks, and...great job! My issue is that I don't know enough about how this new UI was setup for me to run it on my NodeMCU. Are there instructions coming soon for how to implement this new UI? It looks great and I would love to use it, but my instance just keeps loading the original index.htm 
Simply uploading the index2.htm file did not make a difference for me, sadly.

**Comment by toblum** [comment]
Hi @IIAIronWolf,

uploading index2.htm and calling http://<mc_lighting_adress>/index2.htm should usually do the trick.

Regards
Tobias
